#!/usr/bin/env python
import sys
import time
from subprocess import Popen,PIPE

materialnum = int(float(sys.argv[1]))

def get_material():
    return int(Popen(['halcmd getp plasmac_run.material-change-number'], stdout=PIPE, shell=True).communicate()[0].strip())

def get_change():
    return int(Popen(['halcmd getp plasmac_run.material-change'], stdout=PIPE, shell=True).communicate()[0].strip())

def set_material(material):
    Popen(['halcmd setp plasmac_run.material-change-number %d' %(material)], shell=True)

def set_change(value):
    Popen(['halcmd setp plasmac_run.material-change %d' %(value)], shell=True)

set_change(0)
if materialnum != get_material():
    set_material(materialnum)
    start = time.time()
    while get_change() == 0:
        if time.time() > start + 3:
            print("T%d: timeout waiting for material-change" %(materialnum))
    if get_change() < 0:
        print("Material #%d: does not exist" %(materialnum))
set_change(0)
exit()
